### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by eason8479** [eason8479/MNT_group3#1]
# Things need to find
- [ ] find thermo sensor
- [ ] find a relay (or any thing that can turn off the machine)
- [ ] find print model (tiny, had a range of defculity, about 4-5 different models ) 

# Model
input for model
- [ ] x cord
- [ ] y cord
- [ ] base plate temp
- [ ] plate levle
- [ ] nozel temp

output 
- [ ]succes or fail
